---
- hosts: all
  become: true 
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: add server name to nginx html
      lineinfile:
       dest: /usr/share/nginx/html/index.html
       insertafter: "^<p><em>Thank you for using nginx."
       line: <p>hello from web server-{{ ansible_eth1.ipv4.address }}</p>




